# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-19 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('name', models.CharField(max_length=100)),
                ('aicte_id', models.IntegerField(blank=True, null=True)),
                ('institute_id', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Office Mobile No')),
                ('fax', models.CharField(blank=True, max_length=20, null=True, verbose_name='Office Mobile No')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Office E-mail')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
